% CONFIG FILE
ROOT = '<root_path_to_scripts>\'; % with ending '\'

global GIT_PATH % to access to git's commitID
GIT_PATH = 'C:\Users\<USERNAME>\AppData\Local\Programs\Git\bin\git.exe'; % for Windows users

% addpaths
addpath(ROOT);
addpath([ROOT,'helpers']);

% to access to the data generated by hand
global manualValue_file
manualValue_file = [ROOT,'data\manualValue_file.mat'];
